### ISSUE TITLE
make: *** [sub-shared-make_first] 错误 3

### ISSUE THREAD

**Issue by tsuibin** [qtcn/tianchi#40]
cd shared/ && ( test -f Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /data/tianchi/build/shared/shared.pro -o Makefile ) && make -f Makefile 
Project ERROR: Unknown module(s) in QT: script
make: *** [sub-shared-make_first] 错误 3

6位linux系统

**Comment by XChinux** [comment]
这个似乎是没有安装Qt5Script模块导致的
