### ISSUE TITLE
make all error

### ISSUE THREAD

**Issue by tsuibin** [qtcn/tianchi#44]
workstation /data/tianchi/build$ make all                                                master 
cd shared/ && ( test -f Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /data/tianchi/build/shared/shared.pro -o Makefile ) && make -f Makefile all
Project ERROR: Unknown module(s) in QT: script
make: *** [sub-shared-all] 错误 3

**Comment by XChinux** [comment]
现在还有这个问题么?

**Comment by XChinux** [comment]
这是没有安装Qt5Script模块导致的
