### ISSUE TITLE
真的 for Windows / Linux / MacOS 吗？

### ISSUE THREAD

**Issue by mahiuchun** [qtcn/tianchi#91]
「  4. 所有源代码以 GBK 的编码格式保存，以便兼容简体中文，并支持所有编译器。」完全就是错误的，真正支持所有编译器的编码是带BOM的UTF-8。Linux和OSX默认早就不要非UTF-8编码，你就算强制改了编译环境的设置，到了客户的机器上那一样悲剧。

BOM的知识参见：http://en.wikipedia.org/wiki/Byte_order_mark

**Comment by XChinux** [comment]
目前这种代码保存为GBK的方式，我从2008年到现在使用得都正常。将源代码由UTF-8改为GBK,就是因为msvc2008的问题.
